### ISSUE TITLE
Update version in npm

### ISSUE THREAD

**Issue by locomoco28** [WaeCo/node-bluez#22]
The version of [bluez on npm](https://www.npmjs.com/package/bluez) is 0.3.3, would it be possible to update it to 0.4.0? :)

**Comment by WaeCo** [comment]
I am still testing the changes, since they might break existing code I want to be sure it works.
In the meantime you can use the current version by installing directly from github:
`npm install git+https://github.com/WaeCo/node-bluez.git`

Feedback is always appreciated, even if it works for you.
I will leave this open until the version is published.

**Comment by WaeCo** [comment]
Published in npm as 0.4.1
